day10/MyPortfolio/Models/Board.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyPortfolio.Models
{
    public class Board
    {
        [Key]
        public int Id { get; set; } // PK

        [Required(ErrorMessage = "이름은 필수입니다")]
        [MaxLength(50)]  // NVARCHAR(50) 사이즈 지정하려면
        [DisplayName("이름")]
        public string Name { get; set; } // 작성자명

        [Required(ErrorMessage = "아이디는 필수입니다")]
        [MaxLength(20)]
        [DisplayName("아이디")]
        public string UserId { get; set; } // 작성자 아이디

        [Required(ErrorMessage = "제목은 필수입니다")]
        [MaxLength(250)]
        [DisplayName("제목")]
        public string Title { get; set; } // 게시글 제목

        [Required(ErrorMessage = "내용은 필수입니다")]
        [DisplayName("내용")]
        public string Contents { get; set; } // 게시글 내용

        [DisplayName("조회수")]
        public int Hit { get; set; } // 읽은 횟수

        [DisplayName("작성일")]
        public DateTime RegDate { get; set; } // 게시글 작성일자

        // Nullable 변수로 변경
        [DisplayName("수정일")]
        public DateTime? ModDate { get; set; } // 게시글 최종 수정일자

    }
}

day10/MyPortfolio/Models/ErrorViewModel.cs
namespace MyPortfolio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

day10/MyPortfolio/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPortfolio.Data;
using MyPortfolio.Models;

namespace MyPortfolio.Controllers
{
    public class BoardController : Controller
    {
        private readonly AppDbContext _context;

        public BoardController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Board
        public async Task<IActionResult> Index()
        {
            return View(await _context.Board.ToListAsync());
        }

        // GET: Board/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Board
                .FirstOrDefaultAsync(m => m.Id == id);
            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        // GET: Board/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Board/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UserId,title,Contents,Hit,RegDate,ModDate")] Board board)
        {
            if (ModelState.IsValid)
            {
                _context.Add(board);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Board/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Board.FindAsync(id);
            if (board == null)
            {
                return NotFound();
            }
            return View(board);
        }

        // POST: Board/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UserId,title,Contents,Hit,RegDate,ModDate")] Board board)
        {
            if (id != board.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(board);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoardExists(board.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Board/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Board
                .FirstOrDefaultAsync(m => m.Id == id);
            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        // POST: Board/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var board = await _context.Board.FindAsync(id);
            if (board != null)
            {
                _context.Board.Remove(board);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoardExists(int id)
        {
            return _context.Board.Any(e => e.Id == id);
        }
    }
}

day10/MyPortfolio/Controllers/ContactController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio.Controllers
{
    public class ContactController : Controller
    {
        // GET: ContactController
        public ActionResult Index()
        {
            return View();
        }
    }
}

day10/MyPortfolio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyPortfolio.Models;
using System.Diagnostics;

namespace MyPortfolio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

day10/MyPortfolio/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

day10/MyPortfolio/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

day10/MyPortfolio/Views/Board/Create.cshtml
@model MyPortfolio.Models.Board

@{
    ViewData["Title"] = "Board";
}

<section class="py-5">
    <div class="container px-5">
        <div class="row px-2">
            <div class="col-md">
                <!-- Submit 버튼누르면 Post 메서드가 발생 -->
                <form asp-controller="Board" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="mb-3 row">
                        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label asp-for="UserId" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="UserId" class="form-control" />
                            <span asp-validation-for="UserId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Contents" class="control-label"></label>
                        <input asp-for="Contents" class="form-control" />
                        <span asp-validation-for="Contents" class="text-danger"></span>
                    </div>
                    <div class="form-group pt-3">
                        <input type="submit" value="저장" class="btn btn-primary" />
                        <a asp-controller="Board" asp-action="Index" class="btn btn-success">목록</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

day10/MyPortfolio/Views/Board/Delete.cshtml
@model MyPortfolio.Models.Board

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hit)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

day10/MyPortfolio/Views/Board/Details.cshtml
@model MyPortfolio.Models.Board

@{
    ViewData["Title"] = "Board";
}

<section class="py-5">
    <div class="container px-5">
        <div class="row px-2">
            <div class="col-md">
                <!-- Submit 버튼누르면 Post 메서드가 발생 -->
                <form asp-controller="Board" asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="mb-3 row">
                        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label asp-for="UserId" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="UserId" class="form-control" />
                            <span asp-validation-for="UserId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Contents" class="control-label"></label>
                        <input asp-for="Contents" class="form-control" />
                        <span asp-validation-for="Contents" class="text-danger"></span>
                    </div>
                    <!-- 화면에는 나오지 않지만 값을 들고 있음 -->
                    <input asp-for="RegDate" type="hidden" />
                    <input asp-for="ModDate" type="hidden" />
                    <div class="form-group pt-3">
                        <input type="submit" value="저장" class="btn btn-primary" />
                        <a asp-controller="Board" asp-action="Index" class="btn btn-success">목록</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

day10/MyPortfolio/Views/Board/Edit.cshtml
@model MyPortfolio.Models.Board

@{
    ViewData["Title"] = "Board";
}

<section class="py-5">
    <div class="container px-5">
        <div class="row px-2">
            <div class="col-md">
                <!-- Submit 버튼누르면 Post 메서드가 발생 -->
                <form asp-controller="Board" asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="mb-3 row">
                        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label asp-for="UserId" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="UserId" class="form-control" />
                            <span asp-validation-for="UserId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Contents" class="control-label"></label>
                        <input asp-for="Contents" class="form-control" />
                        <span asp-validation-for="Contents" class="text-danger"></span>
                    </div>
                    <!-- 화면에는 나오지 않지만 값을 들고 있음 -->
                    <input asp-for="RegDate" type="hidden" />
                    <input asp-for="ModDate" type="hidden" />
                    <div class="form-group pt-3">
                        <input type="submit" value="저장" class="btn btn-primary" />
                        <a asp-controller="Board" asp-action="Index" class="btn btn-success">목록</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

day10/MyPortfolio/Views/Board/Index.cshtml
@model IEnumerable<MyPortfolio.Models.Board>

@{
    ViewData["Title"] = "Board";
}

<style>
    /* 마우스가 없을땐 밑줄없이 */
    a {
        color: black;
        text-decoration: none;
    }
        /* 마우스가 올라갔을때만 밑줄 */
        a:hover {
            text-decoration: underline;
        }
</style>

<section class="py-5">
    <div class="container px-5">
        <p class="px-1">
            <a asp-controller="Board" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-file-earmark-plus-fill"></i>&nbsp;글 작성
            </a>
        </p>
        <table class="table table-light table-striped">
            <thead>
                <tr class="table-primary">
                    <th style="width:8rem;">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th style="width:8rem;">
                        @Html.DisplayNameFor(model => model.UserId)
                    </th>
                    <th style="width:17rem;">
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    @* <th>
                    @Html.DisplayNameFor(model => model.Contents)
                    </th> *@
                    <th style="width:6rem;">
                        @Html.DisplayNameFor(model => model.Hit)
                    </th>
                    <th style="width:7rem;">
                        @Html.DisplayNameFor(model => model.RegDate)
                    </th>
                    <th style="width:7rem;">
                        @Html.DisplayNameFor(model => model.ModDate)
                    </th>
                    @* <th></th> *@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserId)
                        </td>
                        <td>
                            <a asp-controller="Board" asp-action="Details" asp-route-id="@item.Id">
                                @Html.DisplayFor(modelItem => item.Title)
                            </a>
                        </td>
                        @* <td>
                    @Html.DisplayFor(modelItem => item.Contents)
                    </td> *@
                        <td class="text-end pe-5">
                            @Html.DisplayFor(modelItem => item.Hit)
                        </td>
                        <td>
                            @* @Html.DisplayFor(modelItem => item.RegDate) *@
                            @Convert.ToDateTime(item.RegDate).ToString("yyyy-MM-dd")
                        </td>
                        <td>
                            @* @Html.DisplayFor(modelItem => item.ModDate) *@
                            @if (item.ModDate != null)
                            {
                                @Convert.ToDateTime(item.ModDate).ToString("yyyy-MM-dd")
                            }
                        </td>
                        @* <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td> *@
                    </tr>
                }
            </tbody>
        </table>

    </div>
</section>

day10/MyPortfolio/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contact";
}



<!-- Page content-->
<section class="py-5">
    <div class="container px-5">
        <!-- Contact form-->
        <div class="bg-light rounded-4 py-5 px-4 px-md-5">
            <div class="text-center mb-5">
                <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                <h1 class="fw-bolder">메일주세요!</h1>
                @* <p class="lead fw-normal text-muted mb-0">Let's work together!</p> *@
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-6">
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- * * SB Forms Contact Form * *-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- This form is pre-integrated with SB Forms.-->
                    <!-- To make this form functional, sign up at-->
                    <!-- https://startbootstrap.com/solution/contact-forms-->
                    <!-- to get an API token!-->
                    <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                        <!-- Name input-->
                        <div class="form-floating mb-3">
                            <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                            <label for="name">Full name</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <!-- Email address input-->
                        <div class="form-floating mb-3">
                            <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                            <label for="email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                        <!-- Phone number input-->
                        <div class="form-floating mb-3">
                            <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
                            <label for="phone">Phone number</label>
                            <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                        </div>
                        <!-- Message input-->
                        <div class="form-floating mb-3">
                            <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                            <label for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                        </div>
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                                To activate this form, sign up at
                                <br />
                                <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                            </div>
                        </div>
                        <!-- Submit error message-->
                        <!---->
                        <!-- This is what your users will see when there is-->
                        <!-- an error submitting the form-->
                        <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                        <!-- Submit Button-->
                        <div class="d-grid"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

day10/MyPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - KyeongMin Portfolio</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Custom Google font 한글 폰트로 변경-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet">
    <!-- Bootstrap Icon CDN-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- 기존 vs 부트스트랩에서 초신 부트스트랩 CDN 변경-->
   @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPortfolio.styles.css" asp-append-version="true" />
    *@ <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="~/css/styles.css"/>
</head>
 <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                <a class="navbar-brand" href="/"><span class="fw-bolder text-primary">KyeongMin Portfolio</span></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">HOME</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Resume" asp-action="Index">RESUME</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller=Project asp-action="Index">PROJECTS</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller=Board asp-action="Index">BOARD</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Contact" asp-action="Index">CONTACT</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!--메인컨텍스트 / 페이지마다 변경될 부분!!-->
            <div>
            @RenderBody()
            </div>
        </main>
        <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; localhost 2024</div></div>
                    <div class="col-auto">
                        <a class="small" href="#!">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Terms</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- jQuery 추가 -->
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- ASP.NET Core에 페이지에 들어가는 스크립트 영역-->
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

    